config/routes.rb
ZPrototype::Application.routes.draw do

  root :to => 'restaurants#index'

  resources :restaurants, only: [:index, :show] do
    resources :reviews, only: [:create] do
    end
  end

  get 'restaurants/l/:location' => 'restaurants#location', as: :location
  get 'restaurants/l/:location/categories/:category' => 'restaurants#category', as: :category
end

app/models/restaurant.rb
class Restaurant
  include Mongoid::Document
  include Mongoid::Timestamps

  NEW_DELHI = 'New Delhi'
  BANGALORE = 'Bangalore'
  AHMEDABAD = 'Ahmedabad'
  MUMBAI = 'Mumbai'
  CITIES = [NEW_DELHI, BANGALORE, AHMEDABAD, MUMBAI]

  C_DINE_OUT = 'Dine-Out'
  C_DELIVERY = 'Delivery'
  C_NIGHT_LIFE = 'Night Life'
  C_CAFES = 'Cafes'
  CATEGORIES = [C_DELIVERY, C_DINE_OUT, C_NIGHT_LIFE, C_CAFES]

  field :name, type: String
  validates :name, presence: true

  field :address, type: String

  embeds_many :reviews

  field :city, type: String
  validates :city, inclusion: {in: CITIES}

  field :categories, type: Array, default: []
  #validates :categories, inclusion: {in: CATEGORIES}, allow_blank: true

  field :overall_rating, type: Float

end

app/models/review.rb
class Review
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :restaurant

  field :name, type: String
  validates :name, presence: true

  field :rating, type: Integer
  validates :rating, numericality: {greater_than: 0, less_than_or_equal_to: 10}

  field :content, type: String

  before_save :calculate_overall_rating

  def calculate_overall_rating
    all_ratings = restaurant.reviews.map(&:rating)
    restaurant.overall_rating = ((all_ratings.inject(0.0) { |sum, el| sum + el } )/ all_ratings.size)
    restaurant.save
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  field :name, type: String
  field :email, type: String


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @locations = Restaurant::CITIES
  end

  def location
    @location = params[:location]

    @all_categories = Restaurant::CATEGORIES
    @categories = Restaurant.where(city: @location).distinct(:categories)
  end

  def category
    @location = params[:location]
    @category = params[:category]

    @restaurants = Restaurant.where(city: @location, categories: @category)
    @categories = Restaurant::CATEGORIES
  end

  def show
    id= params[:id]

    @restaurant = Restaurant.find(id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    flash[:error] = nil
    restaurant_id = params[:restaurant_id]
    content = params[:review][:content]
    rating = params[:review][:rating].to_i
    name = params[:review][:name]

    @restaurant = Restaurant.find(restaurant_id)
    @review = @restaurant.reviews.create(content: content, rating: rating, name: name)
    flash[:error] = @review.errors.full_messages.join(', ') if !@review.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZPrototype</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_review.html.erb
<p class="content"><%= review.content%></p>
<div class="by">By: <i><%= review.name%></i><span class='r-tags'> (rated: <%= review.rating%> )</span></div>

app/views/restaurants/_write_review.html.erb
<div class="space add-rev">
  <div class="main"><a href="javascript:">Write review: </a></div>

  <div id="form-start" style="display: none;">
    <%= form_for(@restaurant.reviews.new, url: "/restaurants/#{@restaurant.id.to_s}/reviews", method: 'post', remote: true) do |f|%>
      <div>
        <span class="lbl"><%= f.label(:name, 'Name: ') %></span>
        <span class="lbl"><%= f.text_field(:name) %></span>
      </div>
      <div class="clear"></div>
      <div>
        <span class="lbl"><%= f.label(:review, 'Review:')%></span>
        <span class="lbl"><%= f.text_area(:content, size: '28x5')%><span>
      </div>
      <div class="clear"></div>
      <div>
        <span class="lbl"><%= f.label(:rating, 'Rating (between 1 to 10 )') %></span>
        <span class="lbl"><%= f.text_field(:rating)%></span>
      </div>
      <div class="clear"></div>
      <div><%= f.submit('Submit') %></div>
      <div class="clear"></div>
    <% end %>
  </div>
</div>

app/views/restaurants/category.html.erb
<div class="l-box">
  <ul>
    <span class="loc-sep l-size">|</span>
    <% @categories.each do |category| %>
      <li class="c-list">
        <%= link_to category, category_path(location: @location, category: category), class: ((@category == category) ? "selected" : "")%>
        <span class="loc-sep l-size">|</span>
      </li>
    <% end %>
  </ul>
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li>
        <h3><%= link_to restaurant.name, restaurant_path(restaurant)%><h3>
      </li>
    <% end %>
  </ul>

  <div class="loc-sep">
    <i><%= link_to 'back', root_path%></i>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="c-box">
  <h2>Select Location:</h2>
  <span class="loc-sep l-size">|</span>
  <% @locations.each do |location| %>
    <span class='loc-sep'><%= link_to location, location_path(location: location) %> <span>
    <span class="loc-sep l-size">|</span>
  <% end %>
</div>

app/views/restaurants/location.html.erb
<div class="c-box">
  <h2>Select Category in <%= @location%>:</h2>
  <span class="loc-sep l-size">|</span>
  <% @all_categories.each do |category| %>
    <span class="loc-sep">
      <%= @categories.include?(category) ? link_to(category, category_path(location: @location, category: category)) : category%>
    </span>
    <span class="loc-sep l-size">|</span>
  <% end %>
  <div class="back">
    <i><%= link_to 'back', root_path%></i>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="l-box">
  <div class="space"><span class="r-name"><%= @restaurant.name%></span><span class="r-city"><%= @restaurant.city%></span></div>
  <div class="space r-address"><%= @restaurant.address%></div>
  <div class="space r-tags"><%= @restaurant.categories.join(', ')%></div>

  <div class="space r-reviews">
    <div>Reviews: <span class="r-tags"><% if @restaurant.overall_rating.present?%>(rated: <%= @restaurant.overall_rating.round(1) %> )<% end %></span><div>
    <ul class='rev-list'>
      <% @restaurant.reviews.each do |review|%>
        <li>
          <%= render partial: 'review', locals: {review: review} %>
        </li>
      <% end %>
    </ul>
  </div>

  <%= render partial: 'write_review'%>
</div>

app/views/reviews/_write_review.html.erb
<div class="space add-rev" id="write-review">
  <div class="main">Write review: </div>

  <% if flash[:error].present? %>
    <div class='errors'><%= flash[:error] = "Successfully created..."%></div>
  <% end %>
  <%= form_for(@restaurant.reviews.new, url: "/restaurants/#{@restaurant.id.to_s}/reviews", method: 'post', remote: true) do |f|%>
    <div>
      <span class="lbl"><%= f.label(:name, 'Name: ') %></span>
      <span class="lbl"><%= f.text_field(:name) %></span>
    </div>
    <div class="clear"></div>
    <div>
      <span class="lbl"><%= f.label(:review, 'Review:')%></span>
      <span class="lbl"><%= f.text_area(:content, size: '28x5')%><span>
    </div>
    <div class="clear"></div>
    <div>
      <span class="lbl"><%= f.label(:rating, 'Rating (between 1 to 10 )') %></span>
      <span class="lbl"><%= f.text_field(:rating)%></span>
    </div>
    <div class="clear"></div>
    <div><%= f.submit('Submit') %></div>
    <div class="clear"></div>
  <% end %>
</div>

app/views/reviews/create.js.erb
$('.errors').remove();
<% if !flash[:error] %>
  $('.rev-list').append("<li><%= escape_javascript(render(partial: 'restaurants/review', locals: {review: @review}))%></li>");
  $('#new_review')[0].reset();
<% else %>
  $('#new_review').prepend("<div class='errors'><%= flash[:error]%></div>")
<% end %>